name: harcha_maquinaria
description: Una app Flutter para control de maquinaria Harcha

environment:
  sdk: '>=3.0.0 <4.0.0'

flutter:  
  uses-material-design: true
  
  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  logger: ^2.6.0
  flutter_svg: ^2.0.7
  webview_flutter: ^4.13.0
  android_intent_plus: ^3.1.6
  flutter_html: ^3.0.0-beta.2
  path_provider: ^2.0.14
  url_launcher: ^6.3.1
  html: ^0.15.6
  firebase_performance: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0