name: harcha_maquinaria
description: Una app Flutter para control de maquinaria Harcha

environment:
  sdk: '>=3.0.0 <4.0.0'

flutter:  
  uses-material-design: true
  
  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  image_picker: ^1.0.4 
  logger: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0