// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA09fQCsx1mOJJzByxsc8SL2wVODdM3jEQ',
    appId: '1:982164175631:web:4754bbfbc3393fd3119c7a',
    messagingSenderId: '982164175631',
    projectId: 'harchaappfront',
    authDomain: 'harchaappfront.firebaseapp.com',
    storageBucket: 'harchaappfront.firebasestorage.app',
    measurementId: 'G-Y1PQ328V2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCclJP9KDFRud_WOTsxEJ8BCw-MPIoB1wk',
    appId: '1:982164175631:android:10ec50502528f173119c7a',
    messagingSenderId: '982164175631',
    projectId: 'harchaappfront',
    storageBucket: 'harchaappfront.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0jqbPF55iO9a8LS4RTc-yW7K4K2i-J5A',
    appId: '1:982164175631:ios:eaa6c07282ef3cf1119c7a',
    messagingSenderId: '982164175631',
    projectId: 'harchaappfront',
    storageBucket: 'harchaappfront.firebasestorage.app',
    iosBundleId: 'com.example.harchaMaquinaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0jqbPF55iO9a8LS4RTc-yW7K4K2i-J5A',
    appId: '1:982164175631:ios:eaa6c07282ef3cf1119c7a',
    messagingSenderId: '982164175631',
    projectId: 'harchaappfront',
    storageBucket: 'harchaappfront.firebasestorage.app',
    iosBundleId: 'com.example.harchaMaquinaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA09fQCsx1mOJJzByxsc8SL2wVODdM3jEQ',
    appId: '1:982164175631:web:dc463e94692f3a61119c7a',
    messagingSenderId: '982164175631',
    projectId: 'harchaappfront',
    authDomain: 'harchaappfront.firebaseapp.com',
    storageBucket: 'harchaappfront.firebasestorage.app',
    measurementId: 'G-4HCR9J141V',
  );
}
