name: Deploy Flutter PWA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.32.8'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Flutter Web PWA
      run: flutter build web --release --dart-define=BASE_URL=${{ secrets.BASE_URL }}
      
    - name: Install Firebase CLI
      run: npm install --global firebase-tools

    # - name: Pull Firebase Environment Information
    #   run: firebase functions:config:get > .runtimeconfig.json
    #   working-directory: ./build/web

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --token=${{ secrets.FIREBASE_TOKEN }}  --project 982164175631 --public build/web
      working-directory: ./build/web