name: Deploy Flutter PWA to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.32.8'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Flutter Web PWA
      run: flutter build web --release --dart-define=BASE_URL=${{ secrets.BASE_URL }}
      
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
      
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      working-directory: ./build/web
      
    - name: Deploy to Vercel Production
      run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
      working-directory: ./build/web